/**
 * The satire engine. Big pools of sassy one-liners poking fun at every corner
 * of software-industry life. Use pick() to cycle through without repeating the
 * last one shown from that pool. Add more lines freely — this is THE place.
 */

/** Floating manager / VC / recruiter / exec interruptions (toasts). */
export const MANAGER_QUIPS: string[] = [
  'PM: Can we add dark mode by EOD?',
  'CEO: I told the board it ships Friday.',
  'PM: Quick question — is the rewrite done?',
  'Sales: I promised the client this feature. It does not exist.',
  'VC: Have you considered AI?',
  'VC: Have you considered MORE AI?',
  'VC: What if the AI had its own AI?',
  'Designer: I moved the button 2px. Reship.',
  'Manager: Why is velocity down?',
  'Manager: Let’s double the velocity AND the quality. And halve the team.',
  'PM: It works on my machine, so…',
  'Recruiter: We hired 4 more. They start Monday. No desks though.',
  'Legal: Please remove that comment from the code.',
  'Legal: Also that variable name. And that one.',
  'CTO: We are now a Rust shop. Effective immediately.',
  'CTO: We are now a Go shop. I read a blog post.',
  'Intern: I force-pushed to main. Sorry?',
  'Intern: What does “rm -rf” do? Asking after.',
  'Investor: What is your moat? Is the moat AI?',
  'PM: Just a small change, should be 5 minutes.',
  'PM: This is a tiny tweak. (It is a new product.)',
  'Ops: The free tier expired. In production.',
  'CEO: We are pivoting to an AI-first company.',
  'CEO: We are pivoting away from AI. Too expensive.',
  'CEO: We are pivoting to pivoting. It’s a methodology now.',
  'PM: Can the AI write the tests? And the code? And the PRD? And me?',
  'HR: Reminder that we are a family. (Layoffs Thursday.)',
  'HR: The family is downsizing for the family’s benefit.',
  'Manager: Let’s circle back on that offline.',
  'Manager: Let’s take this conversation… to another, longer meeting.',
  'Manager: This should be a quick win.',
  'Manager: Stretch goal: do it twice as fast, perfectly, by lunch.',
  'PM: The customer is also the CEO’s nephew.',
  'Scrum Master: You forgot to update the ticket.',
  'Scrum Master: The burndown chart is burning up.',
  'Scrum Master: Did everyone enjoy retro? There’s another tomorrow.',
  'PM: Can we make the logo bigger AND smaller?',
  'PM: Make it minimalist but add 12 more buttons.',
  'Exec: Why don’t we just use blockchain?',
  'Exec: Put the blockchain on the cloud. The AI cloud.',
  'Exec: Our competitor shipped it. In a weekend. Allegedly.',
  'Sales: Does it integrate with Salesforce? Say yes.',
  'Sales: I already demoed the feature we haven’t built.',
  'PM: We’ll fix it in v2. (There is no v2.)',
  'CEO: Return-to-office is mandatory. The office is a WeWork. In another city.',
  'CEO: Hybrid means in-office five days, remotely judged.',
  'Recruiter: Must have 8 years of a 3-year-old framework.',
  'Recruiter: Rockstar ninja unicorn wizard. Pays in “exposure.”',
  'Finance: Why is the AWS bill a phone number?',
  'Finance: We optimized costs by deleting the backups.',
  'PM: Let’s timebox this. The box is 20 minutes. For 6 months of work.',
  'Designer: Can it pop more? Make it pop. Now too poppy.',
  'Stakeholder: I don’t know what I want, but not this.',
  'Stakeholder: I’ll know it when I see it. I won’t.',
  'Manager: Great news, you’re now also the DevOps team.',
  'Manager: And the QA team. And the security team. Congrats.',
  'PM: The deadline moved up. To yesterday.',
  'PM: We’re agile, so the deadline is whenever I panic.',
  'CEO: We’re thought leaders now. Please tweet. Daily. Insightfully.',
  'Security: You hardcoded the key again, didn’t you.',
  'Security: It’s in the public repo. With a README explaining it.',
  'VC: We want hockey-stick growth on a flat budget.',
  'VC: Down round, but we’re calling it a “focus round.”',
  'PM: Can we A/B test having no features?',
  'Manager: Document everything. Starting after this sprint. Forever.',
  'Client: Make it like Uber, but for spreadsheets.',
  'Client: Make it like ChatGPT, but it’s a to-do list.',
  'Board: What’s our AI strategy for our AI strategy?',
  'Marketing: We launched! Engineering, please build it now.',
  'Marketing: The press release is live. The product is a Figma.',
  'PM: Quick sync? It’s 4:55 on Friday.',
  'Director: We’re “flattening the org.” Your manager’s manager is now you.',
  'OKR Owner: Your key result has a key result now.',
  'Manager: Why didn’t the estimate include the unknown unknowns?',
  'Architect: I drew a diagram. It has 40 boxes. Ship the boxes.',
  'PM: Users hate change, so change everything.',
  'CEO: We’re lean now. Lean means you do three jobs.',
  'Data: The metric went up. We don’t know which metric.',
  'PM: Can we ship the beta? Just call the prod the beta.',
  'IT: We’re migrating to the new tool. It’s the old tool, renamed.',
  'Manager: Per my last message (I never sent one).',
  'Sales: The contract is signed. The feature is fictional. Go.',
  'Exec: Let’s leverage synergies to circle back on our north star.',
  'CEO: We don’t have bugs. We have undocumented features at scale.',
  'PM: Add a loading spinner so it feels like it’s doing something.',
];

/** Short pops when you squash an incident. */
export const SQUASH_LINES: string[] = [
  'FIXED',
  'PATCHED',
  'WONTFIX',
  'LGTM 👍',
  'shipped 🤷',
  'works now?',
  '// TODO',
  'git blame',
  'reverted',
  'hotfix',
  'band-aid 🩹',
  'duct tape',
  'it compiles',
  'good enough',
  'merged to main',
  'closed as dupe',
  'cache cleared',
  'off and on again',
  'rubber-ducked',
  'Stack Overflow’d',
  'AI fixed it™',
  'magic ✨',
  'on my machine',
  'NaN problem',
  'sleep(500)',
  'try/catch {}',
  'eslint-disable',
  'one-liner',
  '🎯 squashed',
  'not my code',
  'works in prod 🙏',
  'ship it 🚀',
  'tech debt += 1',
  '// don’t touch',
  'commented out',
  'mocked it',
  'feature now',
  'YOLO',
  '99 bugs left',
  'rm -rf bug',
  'restarted pod',
  'scaled it up',
  'threw money',
  'asked the AI',
  'force-merged',
  'skill issue',
  'works as designed',
  'closed: vibes',
  'TODO: revisit',
  'patched in prod',
  'looks fine 🤷',
  'lol fixed',
  'sudo fix',
  'prayed 🙏',
  'cosmic ray',
  'flaky, retried',
  'works Tuesdays',
  'good for demo',
  'kicked the can',
];

/** Short red pops when a bug detonates into an incident. */
export const INCIDENT_LINES: string[] = [
  'PROD DOWN',
  'PAGED 📟',
  '3AM CALL',
  'ROLLBACK',
  'P0 OPENED',
  'STATUS RED',
  'CUSTOMER TWEETED',
  'CEO NOTICED',
  'DATA LOSS',
  'OOMKilled',
  'NULL POINTER',
  'RACE CONDITION',
  'IT’S DNS',
  'IT’S ALWAYS DNS',
  'OUT OF MEMORY',
  'INFINITE LOOP',
  'DEADLOCK',
  'SEGFAULT',
  'KERNEL PANIC',
  'DB ON FIRE 🔥',
  '500 x 1000',
  'CASCADE FAILURE',
  'PAYMENTS DOWN',
  'WENT VIRAL (bad)',
  'HN FRONT PAGE',
  'RETRO SCHEDULED',
  'CERT EXPIRED',
  'DISK FULL',
  'RATE LIMITED',
  'CORS ERROR',
  'undefined is not',
  'PROD == STAGING?!',
  'BACKUP MISSING',
  'INFRA EVAPORATED',
  'PAGER STORM',
  'WAR ROOM OPEN',
  'SEV-0',
  'CTO IN CHAT',
  'TWITTER KNOWS',
  'REGION DOWN',
  'LOOP OF DOOM',
  'MEMORY LEAK',
  'STACK OVERFLOW',
  'OFF BY ONE',
  'TIMEZONE BUG',
  'LEAP YEAR BUG',
  'unicode 💀',
  'DOUBLE CHARGED',
  'EMAILED EVERYONE',
];

/** Occasional flavor when you SHIP IT. */
export const SHIP_LINES: string[] = [
  'Skipped the tests 😎',
  'Works on my machine',
  'Disabled the linter',
  'Merged without review',
  'Force-pushed to main',
  'Commented out the test',
  'Hardcoded the API key',
  'npm install --force',
  'Squashed 47 commits into “fix”',
  'YOLO deploy 🚀',
  'Friday 4:59pm deploy',
  'TODO: write tests',
  'Wrapped it in try/catch',
  'Copy-pasted from prod',
  'Asked AI, didn’t read it',
  'Shipped the demo as the product',
  '“Temporary” fix #4,012',
  'Deleted the failing test',
  'Pushed to prod, prayed',
  '--no-verify',
  'It’s fine, it’s fine',
  'Shipped on a hunch',
  'Bumped the version, vibes',
  'Renamed “bug” to “feature”',
  'Set timeout to 9 hours',
  'Added another microservice',
  'Threw a Redis at it',
  'Scaled horizontally (panicked)',
  'Cargo-culted a config',
  'Trust me bro deploy',
  'Disabled the alert instead',
  'It passed in CI once',
  'Shipped sober, regret later',
  'Big PR, no description',
  'Approved my own PR',
  'Ship now, document never',
];

/** Occasional flavor when you PAY DOWN. */
export const PAY_LINES: string[] = [
  'Wrote a test 😇',
  'Deleted dead code',
  'Renamed a variable',
  'Added a comment',
  'Paid down a TODO',
  'Upgraded a dependency',
  'Removed a console.log',
  'Refactored one function',
  'Documented… something',
  'Closed 3 ancient tickets',
  'Actual code review',
  'Added a real test',
  'Fixed the flaky test',
  'Untangled one if-else',
  'Deleted a dead feature flag',
  'Read the docs (gasp)',
  'Wrote a runbook',
  'Added a type, removed an “any”',
  'Bumped Node, prayed less',
  'Merged the long-lived branch',
  'Killed a zombie cron job',
  'Set up one alert',
  'Touched the legacy, survived',
  'Made one thing less cursed',
  'Apologized to future me',
];

/** Game-over post-mortem verdicts. */
export const VERDICTS: string[] = [
  'Root cause: “ship it.” Contributing factor: also “ship it.”',
  'The post-mortem will be blameless. The Slack channel will not.',
  'A senior engineer warned you. They have since left for a competitor.',
  'The on-call rotation has filed a formal complaint.',
  'Your tech lead is updating their LinkedIn as we speak.',
  'The rewrite would have fixed this. The rewrite was the problem.',
  'Action item: “add monitoring.” Owner: nobody. Due: never.',
  'The incident channel now has more members than the company.',
  'Five-whys complete. The fifth why was just screaming.',
  'You shipped fast and broke things. Mostly the things.',
  'The board has questions. You have a stack trace.',
  'It was working in the demo. The demo was a screenshot.',
  'Status page updated to a tasteful shade of fire.',
  'Your runbook said “see runbook.”',
  'Customers have discovered the support email exists.',
  'Cause: technical debt. Effect: technical bankruptcy.',
  'The AI suggested rolling back. You overruled the AI.',
  'Postmortem owner reassigned to “future you.”',
  'The intern’s force-push was, statistically, the safest commit.',
  'You achieved infinite scale. Of the outage.',
  'Severity: SEV-0. Vibes: SEV-0.',
  'The retro identified “communication.” It always does.',
  'Uptime this quarter: a confident number with a minus sign.',
  'Your monitoring alerted you. To the monitoring being down.',
  'We’ll add a test for this exact case. Right after the next one.',
  'Lessons learned: none. Lessons documented: also none.',
  'The fix was one line. Finding it cost a relationship.',
  'You scaled the team and the chaos. The chaos won.',
  'It’s not technical debt if you declare moral bankruptcy first.',
  'The standup was 45 minutes. The outage was 46.',
  'Marketing already tweeted the apology. With a typo.',
  'You burned the runway. The runway was also on fire.',
  'Your “quick fix” has a one-year anniversary today.',
  'The legacy system outlived three rewrites and your optimism.',
  'Blameless retro concluded. Everyone privately blamed you.',
  'Cause of death: a TODO from 2019.',
  'The dashboard is green. The dashboard is also a screenshot.',
  'You optimized for velocity and arrived nowhere, fast.',
  'There were tests. They tested whether tests existed.',
  'The vendor’s SLA was a vibe. The vibe expired.',
  'Two weeks of work saved an afternoon of reading docs.',
  'You pivoted so hard you arrived back at the bug.',
  'The AI agent fixed it, then opened 9 new tickets about itself.',
  'Customer trust: gracefully degraded to 503.',
  'The war room is now just a room. With one chair. Yours.',
];

/** Lines a boss throws at you when it attacks. */
export const BOSS_TAUNTS: string[] = [
  'Have you tried turning it off and on?',
  'I AM the legacy system.',
  'There are no comments. There never were.',
  'Who wrote this? Oh. You did.',
  'git blame points… everywhere.',
  'I compile only under a full moon.',
  'My documentation fell off a desk in 2009.',
  'You cannot refactor what you do not understand.',
  'I have 200 dependencies and I trust none of them.',
  'The tests pass. I changed what passing means.',
  'I run on a server nobody can find.',
  'My author retired. To a beach. With my passwords.',
  'Every fix spawns two more of me.',
  'I am also the build system. Surprise.',
  'My config is a YAML that hates you specifically.',
  'I was a “temporary” solution. That was eleven years ago.',
  'Touch me and the cron jobs awaken.',
  'I store dates as strings. All of them. Differently.',
  'My only test is in production. You’re in it now.',
  'Nobody knows what I do. Including me.',
  'I have a 4,000-line function and it’s called helper().',
  'My error messages just say “error”.',
  'I’m written in three languages and zero of them well.',
  'The off switch is load-bearing. Don’t.',
  'I survived the migration. The migration did not.',
  'My uptime is a threat, not a promise.',
  'There’s a `// do not delete` and no one remembers why.',
  'I am held together by one regex and a prayer.',
  'My last maintainer left a note: “good luck.”',
  'I scale infinitely. The bill scales faster.',
  'I have feelings and they are all race conditions.',
  'You patched me? Cute. I have backups of my bugs.',
  'I throw the same exception in 14 dialects.',
  'My uptime dashboard is a single, ominous “?”.',
];

/** Promotion card lines when you defeat a boss and level up. */
export const PROMOTION_LINES: string[] = [
  'Promoted! (No raise.)',
  'New title. Same salary. More on-call.',
  'You’re Senior now. Senior of what, unclear.',
  'Equity granted. Cliff: heat death of the universe.',
  'New responsibilities unlocked. New pay: locked.',
  'You may now approve your own PRs. Please don’t.',
  'A bigger desk. In the same open-plan chaos.',
  'Congrats! You’re now blocking three other teams.',
  'Your calendar is 90% meetings about meetings.',
  'You got a hoodie with the new logo.',
  'You’re a “tech lead” now (it means more Jira).',
  'Welcome to management. RIP your IDE.',
  'You now own a system nobody will explain to you.',
  'Title upgraded. Imposter syndrome upgraded too.',
  'You unlocked: being the on-call escalation point.',
  'Raise denied, but here’s a “Rockstar” Slack badge.',
  'You’re now responsible for the thing you warned them about.',
  'Promotion comes with a mentor. It’s a chatbot.',
  'You’re “Staff” now. It’s like Senior but lonelier.',
  'New level: same bugs, fancier meetings.',
  'You got budget! It’s for stickers.',
  'You now have reports. They have questions. So many.',
  'Congrats, you’re the “process owner” (the process is vibes).',
  'You leveled up into a longer email signature.',
  'Promoted into the meeting that decides the meetings.',
];

/** Menu subtitles, picked at random. */
export const MENU_TAGLINES: string[] = [
  'A satirical incident waiting to happen.',
  'Now with 100% more technical debt.',
  'Move fast. Accrue interest.',
  'It compiles. Ship it.',
  'No tests were written in the making of this game.',
  'Inspired by true events. Yours.',
  'The only winning move is to keep kicking.',
  'Sponsored by your future on-call shift.',
  'Backed by tier-1 VCs and zero unit tests.',
  'Now AI-powered (it’s an if-statement).',
  'Disrupting the disruption space.',
  'Web-scale. Bug-scale. Same thing.',
  '99 problems and they’re all in prod.',
  'Refactoring is for people with runway.',
  'Built different. Built worse, but different.',
  'Your debt, but make it gameplay.',
  'Cloud-native. Sanity-optional.',
  'We don’t do QA, we do hope.',
  'Estimated 5 minutes. (It’s a whole game.)',
  'Blazingly fast at making things worse.',
  'Ship today, regret in Q3.',
  'The standup never ends.',
  'It’s not a bug, it’s a roadmap.',
  'Powered by caffeine and denial.',
];

const _last: Map<string[], number> = new Map();

/** Random pick from a pool, avoiding the immediately-previous result. */
export function pick(pool: string[]): string {
  if (pool.length === 1) return pool[0];
  const prev = _last.get(pool);
  let i = Math.floor(Math.random() * pool.length);
  if (i === prev) i = (i + 1) % pool.length;
  _last.set(pool, i);
  return pool[i];
}
